# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9db84ce09de0fab7119c888911c0867e0c3e3287df3a7806b535dfb4134f3b917cc1f2c062ddeb9bb2ce4be51f5b7f39ddbbdc9b40e0912e345f09a813d437b

test:
  secret_key_base: f483b9812a4f34aa40076a8f0ccf0b225123c254fed1eb0090a6e160b797b05ed58833045b3847c1cda5d7d1887fa2ff49eb1eb06008eaa8ea2b80d9538372a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
